complete -c pixelterm -s h -l help -d "Show help"
complete -c pixelterm -s V -l version -d "Show version"
complete -c pixelterm -s D -l dither -d "Enable dithering"
complete -c pixelterm -l preload -r -a "true false" -d "Enable preloading"
complete -c pixelterm -l alt-screen -r -a "true false" -d "Use alternate screen buffer"
complete -c pixelterm -l clear-workaround -d "Enable clear workaround"
complete -c pixelterm -l work-factor -r -d "Quality/speed tradeoff (1-9, default: 9)"
complete -c pixelterm -l protocol -r -a "auto text sixel kitty iterm2" -d "Output protocol"
complete -c pixelterm -l gamma -r -d "Gamma correction for image rendering"
complete -c pixelterm -l config -r -d "Load configuration file"
complete -c pixelterm -a "(__fish_complete_path)" -d "Image file or directory"
