complete -c pixelterm -s h -l help -d "Show help"
complete -c pixelterm -s V -l version -d "Show version"
complete -c pixelterm -s D -l dither -d "Enable dithering"
complete -c pixelterm -l no-preload -d "Disable preloading"
complete -c pixelterm -l no-alt-screen -d "Disable alternate screen"
complete -c pixelterm -l clear-workaround -d "Enable clear workaround"
complete -c pixelterm -l work-factor -r -d "Quality/speed tradeoff (1-9, default: 9)"
complete -c pixelterm -l term -r -d "Override TERM (default: use environment; fallback: rio)"
complete -c pixelterm -a "(__fish_complete_path)" -d "Image file or directory"
